api:
    prefix: "/api"
    resource: "@AppBundle/Controller/Api"
    type:     annotation

fallback:
    path: /{url}
    defaults: { _controller: AppBundle:Default:index, url: null }
    requirements:
        url: .*