# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    guzzle.client:
        class: GuzzleHttp\Client

    css.converter:
        class: Symfony\Component\CssSelector\CssSelectorConverter
        arguments:
            - false
    app.podcast.refresher:
        class: AppBundle\Service\RefreshPodcast
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@css.converter"

    app.podcast.downloader:
        class: AppBundle\Service\EpisodeDownloader
        arguments:
            - "@guzzle.client"
            - "@doctrine.orm.entity_manager"
            - "%download_directory%"

    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
